# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170529_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='author',
            field=models.CharField(default='anonymous', max_length=64),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to='..\\photos/author'),
        ),
    ]
