# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170529_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='author',
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to='..\\photos/anonymous'),
        ),
    ]
