# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170529_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to=polls.models.user_directory_path),
        ),
    ]
